version: '3'
services:
  php-apache:
    build:
      context: ./php-apache
    environment:
      TZ: "Europe/Berlin"
    ports:
      - 127.0.0.1:80:80
    volumes:
      - ./src:/var/www/html

  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb:/var/lib/mysql
      - ./mariadb.setup:/docker-entrypoint-initdb.d
    environment:
      MYSQL_INITDB_SKIP_TZINFO: 1
      TZ: "Europe/Berlin"
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_DATABASE: "ewa"
      MYSQL_USER: "public"
      MYSQL_PASSWORD: "public"
    env_file: env.txt    

  phpadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 127.0.0.1:8081:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306
    env_file:
      - env.txt
volumes:
    mariadb:
